### ISSUE TITLE
关于用户状态广播刷屏的讨论

### ISSUE THREAD

**Issue by GaryDu0123** [SlightDust/steam_HoshinoBot#2]
用户状态boardcast那边我想是不是应该把同群组的放在一条消息发布

一条一条的发说实话有点刷屏 (比如群里cs2开黑, 打开游戏关闭游戏各是5条消息)

我想是不是可以在代码中加个选择(`combine_mode = True`), 可以用那种类似`steam状态查询`的列表发送, 想看看大家的意见

**Comment by SlightDust** [comment]
好提议。简单一点的话可以改成所有图片放在同一条message里一起发，只改定时任务对应的函数就行。

五一和家里人玩几天，之后改(x)
